# Generated by Django 2.1 on 2018-08-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='excel_file',
            field=models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Upload File'),
        ),
    ]
