# Generated by Django 2.2.10 on 2022-09-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20180822_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_milk_rate', models.CharField(max_length=10, verbose_name='गायीचे दूध')),
                ('milk_rate', models.CharField(max_length=10, verbose_name='म्हशींचे दूध')),
                ('dahi_rate', models.CharField(max_length=10, verbose_name='दही')),
                ('ghee_rate', models.CharField(max_length=10, verbose_name='तूप')),
            ],
        ),
    ]
