# Generated by Django 2.2.10 on 2022-09-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
