# Generated by Django 2.2.10 on 2022-09-19 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20220906_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rate',
            name='cow_milk_rate',
            field=models.CharField(max_length=10, verbose_name='गायीचे दूध /ltr'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='dahi_rate',
            field=models.CharField(max_length=10, verbose_name='दही /kg'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='ghee_rate',
            field=models.CharField(max_length=10, verbose_name='तूप /kg'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='milk_rate',
            field=models.CharField(max_length=10, verbose_name='म्हशींचे दूध /ltr'),
        ),
    ]
