# Generated by Django 2.2.10 on 2022-10-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20220919_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='cow_milk_rate',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='dahi_rate',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='ghee_rate',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='milk_rate',
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
